name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  checks:
    name: Project Checks
    runs-on: ubuntu-18.04
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
      with:
        path: src/github.com/containerd/fifo
        fetch-depth: 25
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - uses: containerd/project-checks@v1.0.2
      with:
        working-directory: src/github.com/containerd/fifo

  linters:
    name: Linters
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-18.04, macos-10.15, windows-2019]

    steps:
      - uses: actions/checkout@v2
        with:
          path: src/github.com/containerd/fifo

      - name: Set env
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: v1.47.1
          working-directory: src/github.com/containerd/fifo

  tests:
    name: Tests
    runs-on: ubuntu-18.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
        with:
          path: src/github.com/containerd/fifo

      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - run: make test
        working-directory: src/github.com/containerd/fifo
